[package]
name = "jwt"
version = "0.1.0"
authors = ["Michael Pankov <work@michaelpankov.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biscuit = "0.5.0"
num = "0.3.1"
serde = "1.0.123"
